@domain=http://localhost:3000


### 
GET {{domain}}/api/notebooks

### @name createNotebook
POST {{domain}}/api/notebooks
Content-Type: application/json

{
    "title": "My 2nd Notebook"
}

### @name getNotebook
@notebookId = kQI06dY3wYZcg-yhcXsaP

GET {{domain}}/api/notebooks/{{notebookId}}

### Update a notebook
PUT {{domain}}/api/notebooks/{{notebookId}}
Content-Type: application/json

{
    "title": "Updated Notebook Title"
}

### Delete a notebook
DELETE {{domain}}/api/notebooks/{{notebookId}}

### Notes Endpoints ###

### Get all notes in a notebook
GET {{domain}}/api/notebooks/{{notebookId}}/notes

### @name createNote
POST {{domain}}/api/notebooks/{{notebookId}}/notes
Content-Type: application/json

{
    "title": "My 2nd Note",
    "content": "This is the content of my first note"
}

### @name getNote
@noteId = 1

GET {{domain}}/api/notebooks/{{notebookId}}/notes/{{noteId}}

### Update a note
PUT {{domain}}/api/notebooks/{{notebookId}}/notes/{{noteId}}
Content-Type: application/json

{
    "title": "Updated Note Title",
    "content": "This is the updated content of my note"
}

### Delete a note
DELETE {{domain}}/api/notebooks/{{notebookId}}/notes/{{noteId}}

### Generate embeddings
POST http://localhost:3000/api/embeddings
Content-Type: application/json

{
    "content": "This is a sample text to generate embeddings from"
}

### Vector Endpoints ###

### Get all vector collections
GET {{domain}}/api/vectors/collections

### Create a vector collection
POST {{domain}}/api/vectors/collections
Content-Type: application/json

{
    "name": "next_qdrant_768",
    "vectorSize": 768
}

### Search for vectors

POST {{domain}}/api/vectors/search
Content-Type: application/json

{
    "question": "Is it possible to scale down a Qdrant Cloud cluster",
    "limit": 2
}


### Ingest data into a vector collection
POST {{domain}}/api/vectors/ingest-data
Content-Type: application/json

{
    "notebookId": "kQI06dY3wYZcg-yhcXsaP"
}

